[package]
name = "god-of-sessions"
version = "0.1.0"
description = "God of Sessions"
authors = ["God of Sessions"]
edition = "2021"
license = "MIT"

[lib]
name = "god_of_sessions_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri = { version = "2", features = [] }

[dev-dependencies]
