import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, LockKeyhole, MessageCircle, ShieldCheck } from "lucide-react";
import morrowImage from "../assets/morrow.png";
import { cn } from "../lib/cn";
import { transitionState } from "../lib/motion";
import type { AppLanguage, BootstrapState } from "../shared/contracts";
import { OperatorMark } from "./OperatorMark";
import { ProviderConnections } from "./ProviderConnections";
import { Button } from "./ui/Button";

export function Onboarding({ state, error, onConnect, onComplete, onLanguageChange }: {
  state: BootstrapState;
  error?: string;
  onConnect(providerId: string, authType: "api_key" | "oauth"): Promise<void>;
  onComplete(language: AppLanguage): Promise<void>;
  onLanguageChange?(language: AppLanguage): void;
}) {
  const [step, setStep] = useState(0);
  const [language, setLanguage] = useState<AppLanguage>(state.language);
  const ko = language === "ko";
  const connected = state.providers.some((provider) => provider.connected);
  const steps = ko ? ["Morrow 만나기", "대화 모델", "야간 작업"] : ["Meet Morrow", "Conversation model", "Overnight"];
  const changeStep = (nextStep: number) => transitionState(() => setStep(nextStep));
  const changeLanguage = (nextLanguage: AppLanguage) => transitionState(() => {
    setLanguage(nextLanguage);
    onLanguageChange?.(nextLanguage);
  });
  return (
    <main className="onboarding-shell grid h-dvh grid-rows-[66px_minmax(0,1fr)_72px] overflow-hidden bg-night text-ink">
      <header className="onboarding-topbar grid grid-cols-[1fr_auto_1fr] items-center border-b border-line-soft bg-night/80 px-7 backdrop-blur-xl">
        <div className="onboarding-brand flex items-center gap-2.5"><OperatorMark size={29} /><span className="flex flex-col max-[620px]:hidden"><strong className="font-mono text-[11px] tracking-[0.11em]">GOD OF SESSIONS</strong><small className="mt-0.5 font-mono text-[9px] tracking-[0.14em] text-ink-faint">MORROW · FIRST LIGHT</small></span></div>
        <div className="onboarding-progress flex items-center gap-1">{steps.map((label, index) => <Button variant="ghost" size="sm" aria-label={label} className={cn("h-12 min-h-0 flex-col gap-1 rounded-lg px-2 font-mono text-[9px] font-normal text-ink-faint shadow-none", index === step && "is-current text-amber", index < step && "is-complete text-teal")} key={label} onClick={() => changeStep(index)}><span className={cn("grid size-6 place-items-center rounded-full border border-line text-[9px]", index === step && "border-amber bg-amber text-[#17120a]", index < step && "border-teal/50 text-teal")}>{index < step ? <Check size={12} /> : index + 1}</span>{label}</Button>)}</div>
        <span />
      </header>

      <section className={`onboarding-canvas onboarding-step onboarding-step--${step} mx-auto grid w-[min(1180px,calc(100%-80px))] grid-cols-[minmax(0,0.85fr)_minmax(380px,1.15fr)] items-center gap-[clamp(48px,8vw,120px)] overflow-hidden max-[900px]:w-[calc(100%-48px)] max-[900px]:grid-cols-1 max-[900px]:gap-8`}>
        {step === 0 && <><div className="onboarding-copy"><span className="eyebrow font-mono text-[10px] font-semibold tracking-[0.16em] text-amber">{ko ? "대화와 파일 작업" : "CONVERSATION AND FILE WORK"}</span><h1 className="mt-5 text-[clamp(48px,5vw,68px)] font-medium leading-[0.98] tracking-[-0.055em]">{ko ? "Morrow와 그냥 이야기하세요." : "Just talk to Morrow."}</h1><p className="mt-5 max-w-[520px] text-[15px] leading-6 text-ink-muted">{ko ? "대화만 해도 좋습니다. 파일이 필요한 부탁은 아래 파일 작업 폴더를 기준으로 처리하고, 바꾸기 전에는 먼저 확인합니다." : "Conversation is enough. Requests that need files use the working folder below as their boundary, and Morrow confirms before making changes."}</p><div className="mt-5 max-w-[520px] rounded-[12px] border border-amber/20 bg-amber/[0.035] p-3"><span className="block font-mono text-[9px] tracking-[0.12em] text-amber">{ko ? "파일 작업 폴더" : "FILE WORKING FOLDER"}</span><code className="mt-1.5 block break-all text-[11px] leading-5 text-ink-muted">{state.rootPath}</code></div><div className="onboarding-language mt-7 border-t border-line-soft pt-5"><span className="font-mono text-[9px] tracking-[0.12em] text-ink-faint">LANGUAGE</span><div className="mt-2 flex gap-2"><Button size="sm" className={language === "en" ? "is-selected border-amber/30 bg-amber/[0.08] text-ink" : ""} onClick={() => changeLanguage("en")}>English</Button><Button size="sm" className={language === "ko" ? "is-selected border-amber/30 bg-amber/[0.08] text-ink" : ""} onClick={() => changeLanguage("ko")}>한국어</Button></div></div></div><div className="onboarding-visual onboarding-visual--morrow grid place-items-center border-0 bg-transparent shadow-none"><div className="onboarding-morrow-stage relative grid place-items-center"><img className="max-h-[min(54vh,560px)] w-auto object-contain saturate-[0.82] drop-shadow-[0_36px_54px_rgb(0_0_0_/_0.44)]" src={morrowImage} alt="Morrow glowing beside a small lamp" /></div></div></>}
        {step === 1 && <><div className="onboarding-copy"><span className="eyebrow font-mono text-[10px] font-semibold tracking-[0.16em] text-amber">{ko ? "대화에 사용할 AI 서비스" : "AI SERVICE FOR CONVERSATION"}</span><h1 className="mt-5 text-[clamp(48px,5vw,68px)] font-medium leading-[0.98] tracking-[-0.055em]">{ko ? "Morrow와 대화할 AI를 연결하세요." : "Connect the AI Morrow talks with."}</h1><p className="mt-5 max-w-[520px] text-[15px] leading-6 text-ink-muted">{ko ? "여기서 연결한 AI 서비스가 Morrow의 답변을 만듭니다. 밤새 일을 맡길 AI는 해당 화면에서 설치와 로그인, 파일 작업 가능 여부를 따로 확인합니다." : "The AI service connected here creates Morrow’s answers. AI used for overnight tasks is checked separately for installation, sign-in, and file access."}</p>{error && <div className="onboarding-error mt-5 flex gap-3 rounded-control border border-danger/25 bg-danger/[0.06] p-3" role="alert"><img className="size-10 object-contain" src={morrowImage} alt="Morrow looking for a connection" /><span className="flex flex-col"><strong className="text-sm text-danger">{ko ? "연결 길을 찾지 못했어요." : "I couldn’t find that connection."}</strong><small className="mt-1 text-xs text-ink-muted">{error}</small></span></div>}</div><div className="onboarding-visual onboarding-visual--providers rounded-panel border border-line bg-surface/70 p-4 shadow-panel backdrop-blur-xl"><ProviderConnections state={state} language={language} compact onConnect={onConnect} onDisconnect={async () => undefined} /></div></>}
        {step === 2 && <><div className="onboarding-copy"><span className="eyebrow font-mono text-[10px] font-semibold tracking-[0.16em] text-amber">{ko ? "밤새 맡길 일 · 한 번 확인" : "OVERNIGHT WORK · ONE CONFIRMATION"}</span><h1 className="mt-5 text-[clamp(48px,5vw,68px)] font-medium leading-[0.98] tracking-[-0.055em]">{ko ? "오늘 밤 맡길 일을 직접 고르세요." : "Choose tonight's work yourself."}</h1><p className="mt-5 max-w-[520px] text-[15px] leading-6 text-ink-muted">{ko ? "Morrow가 가능한 일을 모으면, 실행할 항목과 담당 AI를 고릅니다. 각 항목의 결과, 완료 확인 방법, 파일 변경 범위와 시간을 확인한 뒤 한 번 승인하세요." : "When Morrow gathers possible work, choose the items and AI worker. Review each outcome, verification method, file scope, and timing before one approval."}</p><div className="onboarding-safety-list mt-7 border-t border-line-soft">{[[MessageCircle, ko ? "실행할 일 직접 선택" : "Choose every task", ko ? "체크한 일과 선택한 AI만 계획에 들어갑니다." : "Only checked tasks and the AI you select enter the plan."], [LockKeyhole, ko ? "결과와 파일 범위 먼저 확인" : "Review outcome and file scope", ko ? "무엇을 얻고 어떻게 확인할지, 어디를 바꿀지 먼저 보여줍니다." : "See what you will get, how to verify it, and which files can change."], [ShieldCheck, ko ? "아침에 항목별 결과 확인" : "Review each result in the morning", ko ? "각 결과와 남은 질문을 섞지 않고 따로 확인합니다." : "Review each result and remaining question separately."]].map(([Icon, title, detail], index) => { const SafetyIcon = Icon as typeof MessageCircle; return <span className="flex items-center gap-3 border-b border-line-soft py-3" key={String(title)}><i className={cn("grid size-5 place-items-center text-teal", index === 2 && "needs-approval text-amber")}><SafetyIcon size={14} /></i><b className="flex flex-col font-normal"><strong className="text-sm font-medium">{String(title)}</strong><small className="mt-0.5 text-[11px] text-ink-faint">{String(detail)}</small></b></span>; })}</div></div><div className="onboarding-visual onboarding-visual--chat rounded-panel border border-line bg-surface/55 p-5 shadow-panel"><div className="onboarding-chat-capture flex min-h-[360px] items-center gap-5 rounded-[14px] border border-line-soft bg-night/70 p-10"><img className="size-14 rounded-[16px] border border-amber/20 object-cover" src={morrowImage} alt="Morrow" /><div><small className="font-mono text-[10px] tracking-[0.14em] text-amber">MORROW</small><p className="mt-3 text-base leading-7 text-ink-muted">{ko ? "오늘 밤 진행할 수 있는 일을 찾았어요. 결과와 확인 방법, 파일 범위를 보고 맡길 일을 골라 주세요. 승인한 계획만 시작할게요." : "I found work that can move tonight. Review the outcome, verification, and file scope, then choose what to assign. I’ll start only the plan you approve."}</p></div></div></div></>}
      </section>
      <footer className="onboarding-footer grid grid-cols-[1fr_auto_1fr] items-center border-t border-line-soft bg-night/80 px-7 backdrop-blur-xl"><Button variant="ghost" className="onboarding-back justify-self-start" disabled={step === 0} onClick={() => changeStep(step - 1)}><ArrowLeft size={15} />{ko ? "이전" : "Back"}</Button><span />{step < steps.length - 1 ? <Button variant="primary" className="onboarding-next justify-self-end" onClick={() => changeStep(step + 1)}>{ko ? "계속" : "Continue"} <ArrowRight size={15} /></Button> : <Button variant="primary" className="onboarding-next justify-self-end" onClick={() => void onComplete(language)}>{connected ? (ko ? "대화 시작" : "Enter the room") : (ko ? "모델 없이 둘러보기" : "Look around without a model")} <ArrowRight size={15} /></Button>}</footer>
    </main>
  );
}
