import type {
  ControlBoard,
  MorningBrief,
  NightPlanHistory,
  NightRunDetail,
  NightRunHistory,
  OvernightPlan,
  Provider,
  ProviderSummary,
  Session,
  Snapshot,
  WorkspaceOverview,
} from "./types";

const now = Date.now();

const session = (
  provider: Provider,
  id: string,
  title: string,
  repo: string,
  status: Session["status"],
  minutesAgo: number,
  extra: Partial<Session> = {},
): Session => ({
  id: `${provider}:${id}`,
  provider,
  native_id: id,
  native_kind: "interactive",
  title,
  cwd: `/Users/you/projects/${repo}`,
  repository: repo,
  branch: "main",
  worktree: null,
  created_at: new Date(now - 86_400_000).toISOString(),
  updated_at: new Date(now - minutesAgo * 60_000).toISOString(),
  status,
  status_confidence: status === "running" ? "observed" : "inferred",
  model: null,
  tokens_used: null,
  archived: false,
  parent_native_id: null,
  child_count: 0,
  capabilities: ["discover", "read_metadata", "resume"],
  source_version: "preview",
  signals: [],
  ...extra,
});

const sessions: Session[] = [
  session("cursor", "c1", "세션 관제 화면의 탐색 구조 정리", "godofsessions", "needs_input", 2, {
    signals: ["unread", "pending_plan"],
    branch: "feat/session-index",
  }),
  session("cursor", "c2", "결제 화면 리팩터링 계획", "malgun-app", "blocked", 8, {
    signals: ["blocking_action"],
  }),
  session("claude", "cl1", "권한 설계 검토", "orca", "needs_input", 14, {
    signals: ["agent_waiting"],
    status_confidence: "reported",
  }),
  session("codex", "co1", "네 공급자 커넥터 구현", "godofsessions", "running", 0, {
    native_kind: "subagent",
    child_count: 3,
    model: "gpt-5.6-codex",
    capabilities: ["discover", "read_metadata", "observe_live", "resume", "fork"],
  }),
  session("grok", "g1", "로컬 에이전트 시장 조사", "agent-research", "running", 1, {
    model: "grok-code-fast",
    signals: ["write_lock_recent"],
  }),
  session("claude", "cl2", "API 경계 테스트", "malgun-app", "idle", 23, {
    branch: "fix/api-boundary",
  }),
  session("codex", "co2", "커넥터 위험도 문서화", "godofsessions", "completed", 42, {
    tokens_used: 18420,
  }),
  session("grok", "g2", "대시보드 경쟁 제품 비교", "agent-research", "idle", 76),
  session("cursor", "c3", "온보딩 문구 수정", "fable-project", "idle", 118),
  session("claude", "cl3", "테스트 실패 원인 분석", "orca", "failed", 184),
  session("hermes", "h1", "밤샘 목표 계약 다듬기", "godofsessions", "idle", 210),
  session(
    "openclaw",
    "o1",
    "에이전트 게이트웨이 확인",
    "agent-research",
    "idle",
    240,
  ),
];

const providers: ProviderSummary[] = (
  ["claude", "codex", "grok", "cursor", "hermes", "openclaw"] as Provider[]
).map((provider) => ({
  provider,
  state: provider === "cursor" ? "degraded" : "ready",
  installed: true,
  session_count:
    provider === "claude"
      ? 564
      : provider === "codex"
        ? 54
        : provider === "grok"
          ? 254
          : provider === "cursor"
            ? 252
            : provider === "hermes"
              ? 16
              : 1,
  source_label: "preview",
  message:
    provider === "cursor"
      ? "Cursor 내부 Composer 헤더 형식은 실험적으로 지원됩니다."
      : null,
}));

export const previewSnapshot: Snapshot = {
  generated_at: new Date().toISOString(),
  sessions,
  providers,
  warnings: [],
  privacy_note:
    "원본은 읽기 전용입니다. 관제판은 최근 24시간의 사용자·응답 텍스트를 메모리에서 제한적으로 읽고 저장하지 않습니다.",
};

export const previewControlBoard: ControlBoard = {
  generated_at: new Date().toISOString(),
  read_only: true,
  warnings: [],
  methodology:
    "최근 24시간의 세션을 프로젝트별로 묶고, 명시적인 Hermes Kanban 작업은 별도 작업으로 유지했습니다. 사람 판단과 외부 부작용 가능성은 실행 가능 상태보다 먼저 표시합니다.",
  items: [
    {
      id: "hermes-kanban:default:t_send",
      origin: "hermes_kanban",
      source_id: "t_send",
      project: "default",
      title: "설문 폼을 멘토에게 보내기",
      state: "needs_me",
      source_state: "ready",
      provider: "hermes",
      workspace: null,
      updated_at: new Date(now - 45 * 60_000).toISOString(),
      priority: 1,
      assignee: "worker",
      model_override: null,
      session_ids: [],
      human_gate: "external_action",
      human_gate_reason:
        "외부 전송·배포·삭제·결제 가능성이 있어 unattended 실행 전에 확인해야 합니다.",
      evidence: [
        "Hermes Kanban · default 보드",
        "원본 작업 ID: t_send",
        "담당 프로필: worker",
        "우선순위: 1",
      ],
    },
    {
      id: "project:/Users/you/projects/godofsessions",
      origin: "inferred_session",
      source_id: "/Users/you/projects/godofsessions",
      project: "godofsessions",
      title: "밤샘 목표 계약 다듬기",
      state: "ready",
      source_state: "idle",
      provider: "hermes",
      workspace: "/Users/you/projects/godofsessions",
      updated_at: new Date(now - 210 * 60_000).toISOString(),
      priority: null,
      assignee: null,
      model_override: null,
      session_ids: ["codex:co2", "hermes:h1"],
      human_gate: null,
      human_gate_reason: null,
      evidence: [
        "최근 24시간 세션 2개",
        "2개 제공자에서 같은 프로젝트가 관측됨",
        "가장 최근 상태: Hermes · 유휴",
      ],
    },
    {
      id: "project:/Users/you/projects/agent-research",
      origin: "inferred_session",
      source_id: "/Users/you/projects/agent-research",
      project: "agent-research",
      title: "로컬 에이전트 시장 조사",
      state: "running",
      source_state: "running",
      provider: "grok",
      workspace: "/Users/you/projects/agent-research",
      updated_at: new Date(now - 60_000).toISOString(),
      priority: null,
      assignee: null,
      model_override: "grok-code-fast",
      session_ids: ["grok:g1", "grok:g2", "openclaw:o1"],
      human_gate: null,
      human_gate_reason: null,
      evidence: [
        "최근 24시간 세션 3개",
        "2개 제공자에서 같은 프로젝트가 관측됨",
        "가장 최근 상태: Grok · 작업 중",
      ],
    },
    {
      id: "project:/Users/you/projects/fable-project",
      origin: "inferred_session",
      source_id: "/Users/you/projects/fable-project",
      project: "fable-project",
      title: "온보딩 문구 수정",
      state: "review",
      source_state: "completed",
      provider: "cursor",
      workspace: "/Users/you/projects/fable-project",
      updated_at: new Date(now - 118 * 60_000).toISOString(),
      priority: null,
      assignee: null,
      model_override: null,
      session_ids: ["cursor:c3"],
      human_gate: null,
      human_gate_reason: null,
      evidence: [
        "최근 24시간 세션 1개",
        "1개 제공자에서 같은 프로젝트가 관측됨",
        "가장 최근 상태: Cursor · 완료",
      ],
    },
  ],
};

export const previewWorkspaceOverview: WorkspaceOverview = {
  snapshot: previewSnapshot,
  control_board: previewControlBoard,
  context_index: {
    generated_at: new Date().toISOString(),
    window_hours: 24,
    projects: [
      {
        project: "godofsessions",
        workspace: "/Users/you/projects/godofsessions",
        session_ids: ["codex:co2", "hermes:h1"],
        providers: ["codex", "hermes"],
        excerpt_count: 8,
        truncated: true,
        excerpts: [
          {
            provider: "codex",
            session_id: "codex:co2",
            role: "user",
            text: "자기 전에 overnight로 돌릴 가장 ROI 높은 프로젝트와 공급자를 대신 골라주는 에이전트가 필요해.",
            timestamp: new Date(now - 6 * 60 * 60_000).toISOString(),
          },
          {
            provider: "codex",
            session_id: "codex:co2",
            role: "assistant",
            text: "사용량, 최근 프로젝트 맥락, 사람 확인이 필요한 작업을 함께 보도록 설계하겠습니다.",
            timestamp: new Date(now - 5.8 * 60 * 60_000).toISOString(),
          },
          {
            provider: "hermes",
            session_id: "hermes:h1",
            role: "user",
            text: "Hermes처럼 기억을 찾되 모든 공급자 세션을 프로젝트 단위로 이해해야 해.",
            timestamp: new Date(now - 4.2 * 60 * 60_000).toISOString(),
          },
          {
            provider: "hermes",
            session_id: "hermes:h1",
            role: "assistant",
            text: "원본을 복제하지 않고 첫 맥락과 최신 결론을 임시 발췌로 묶을 수 있습니다.",
            timestamp: new Date(now - 4 * 60 * 60_000).toISOString(),
          },
          {
            provider: "codex",
            session_id: "codex:co2",
            role: "user",
            text: "외부 전송 같은 일은 밤에 자동으로 돌리면 안 돼.",
            timestamp: new Date(now - 70 * 60_000).toISOString(),
          },
          {
            provider: "codex",
            session_id: "codex:co2",
            role: "assistant",
            text: "사람 확인 게이트와 읽기 전용 관제판으로 먼저 검증하겠습니다.",
            timestamp: new Date(now - 65 * 60_000).toISOString(),
          },
        ],
      },
    ],
    warnings: [],
    ephemeral: true,
    methodology:
      "오늘의 사용자·응답 텍스트만 메모리에서 제한적으로 읽으며 별도 데이터베이스에 저장하지 않습니다.",
  },
};

export const previewNightRunHistory: NightRunHistory = {
  generated_at: new Date().toISOString(),
  read_only: true,
  warnings: [],
  methodology:
    "Hermes 전용 보드의 task/task_run과 Codex provider rollout의 clientUserMessageId turn을 읽기 전용으로 결합했습니다.",
  runs: [
    {
      surface: "codex",
      task_id: "turn-preview-codex",
      title: "Codex 야간 실행 복구와 Morning Review 연결",
      project: "godofsessions",
      workspace: "/Users/you/projects/godofsessions",
      status: "done",
      created_at: new Date(now - 7 * 60 * 60_000).toISOString(),
      started_at: new Date(now - 7 * 60 * 60_000).toISOString(),
      completed_at: new Date(now - 4 * 60 * 60_000).toISOString(),
      run_id: null,
      run_status: "completed",
      worker_pid: null,
      session_id: "co1",
      thread_id: "co1",
      turn_id: "turn-preview-codex",
      outcome: "completed",
      summary:
        "Codex rollout 기반 중복 방지와 아침 실행 기록 복구를 구현하고 관련 테스트를 통과했습니다.",
      error: null,
      idempotency_key: "gos-codex-preview-done",
    },
    {
      surface: "hermes",
      task_id: "task-night-running",
      title: "에이전트 메모리 인덱스 검증",
      project: "overnight-eval",
      workspace: "/Users/you/projects/overnight-eval",
      status: "running",
      created_at: new Date(now - 95 * 60_000).toISOString(),
      started_at: new Date(now - 94 * 60_000).toISOString(),
      completed_at: null,
      run_id: 14,
      run_status: "running",
      worker_pid: 48102,
      session_id: "hermes-night-14",
      thread_id: null,
      turn_id: null,
      outcome: null,
      summary: null,
      error: null,
      idempotency_key: "gos-night-preview-running",
    },
    {
      surface: "hermes",
      task_id: "task-night-done",
      title: "세션 커넥터 경계와 회귀 테스트 정리",
      project: "control-plane-notes",
      workspace: "/Users/you/projects/control-plane-notes",
      status: "done",
      created_at: new Date(now - 11 * 60 * 60_000).toISOString(),
      started_at: new Date(now - 11 * 60 * 60_000 + 60_000).toISOString(),
      completed_at: new Date(now - 8 * 60 * 60_000).toISOString(),
      run_id: 9,
      run_status: "done",
      worker_pid: 47381,
      session_id: "hermes-night-9",
      thread_id: null,
      turn_id: null,
      outcome: "completed",
      summary:
        "커넥터별 읽기 경계를 문서화하고 관련 테스트를 추가했습니다. 검증 명령은 모두 통과했습니다.",
      error: null,
      idempotency_key: "gos-night-preview-done",
    },
  ],
};

export const previewMorningBrief: MorningBrief = {
  generated_at: new Date().toISOString(),
  plan_id: "gos-portfolio-preview-m18",
  approved_at: new Date(now - 7 * 60 * 60_000).toISOString(),
  deadline_at: new Date(now + 15 * 60_000).toISOString(),
  plan_state: "needs_attention",
  headline: "1개는 먼저 판단이 필요합니다.",
  attention_count: 1,
  review_count: 1,
  in_progress_count: 1,
  not_started_count: 0,
  reviewed_count: 0,
  read_only: true,
  methodology:
    "최신 승인 계획의 각 계약 식별자를 공급자 원장에 exact-id로 대조하고 사람 판단 필요 순서로 정렬했습니다.",
  warnings: [],
  items: [
    {
      draft_id: "draft-preview-claude",
      project: "malgun-app",
      title: "첫 사용 화면의 회귀 위험 정리",
      surface: "claude",
      capacity_pool: "claude_subscription",
      coordinator_state: "running",
      task_id: null,
      thread_id: null,
      verdict: "needs_attention",
      verdict_reason:
        "coordinator 상태와 대응하는 공급자 실행 기록을 찾지 못했습니다.",
      summary: null,
      error: "Claude fork 영수증은 있지만 완료 transcript가 아직 없습니다.",
      started_at: new Date(now - 75 * 60_000).toISOString(),
      completed_at: null,
      next_action: "중복 실행 없이 원본 기록 확인",
      provenance_verified: false,
      inspectable: false,
      evidence_fingerprint:
        "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
      review_state: "unreviewed",
      reviewed_at: null,
      workspace_evidence: null,
    },
    {
      draft_id: "draft-preview-codex",
      project: "godofsessions",
      title: "Codex 야간 실행 복구와 Morning Review 연결",
      surface: "codex",
      capacity_pool: "codex_subscription",
      coordinator_state: "completed",
      task_id: "turn-preview-codex",
      thread_id: "co1",
      verdict: "ready_to_review",
      verdict_reason:
        "Codex 완료 수명주기와 최종 응답이 모두 있습니다. 실제 변경과 검증은 사람이 확인해야 합니다.",
      summary:
        "Codex rollout 기반 중복 방지와 아침 실행 기록 복구를 구현하고 관련 테스트를 통과했습니다.",
      error: null,
      started_at: new Date(now - 7 * 60 * 60_000).toISOString(),
      completed_at: new Date(now - 4 * 60 * 60_000).toISOString(),
      next_action: "변경 내용과 검증 근거 검토",
      provenance_verified: true,
      inspectable: true,
      evidence_fingerprint:
        "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
      review_state: "unreviewed",
      reviewed_at: null,
      workspace_evidence: {
        state: "changed",
        captured_before: new Date(now - 7 * 60 * 60_000).toISOString(),
        observed_at: new Date(now - 4 * 60 * 60_000).toISOString(),
        finalized: true,
        repository_root: "/Users/you/projects/godofsessions",
        baseline_head: "4503855000000000000000000000000000000000",
        observed_head: "4febebe000000000000000000000000000000000",
        head_changed: true,
        preexisting_dirty_count: 2,
        observed_dirty_count: 3,
        changed_files: [
          {
            path: "src-tauri/src/night_coordinator/morning.rs",
            before_status: null,
            after_status: ".M",
            change: "modified",
          },
          {
            path: "src/components/OvernightView.tsx",
            before_status: ".M",
            after_status: ".M",
            change: "modified",
          },
          {
            path: "docs/overnight-m20.md",
            before_status: null,
            after_status: "??",
            change: "added",
          },
        ],
        attribution:
          "실행 직전 기준선 이후 관측된 최종 작업공간 변화입니다. 다른 로컬 프로세스의 동시 변경까지 단독 귀속하지는 않습니다.",
        warning: "실행 전부터 수정된 파일 2개는 변화 비교에서 분리했습니다.",
      },
    },
    {
      draft_id: "draft-preview-hermes",
      project: "agent-research",
      title: "에이전트 메모리 인덱스 검증",
      surface: "hermes",
      capacity_pool: "grok_subscription",
      coordinator_state: "running",
      task_id: "task-night-running",
      thread_id: null,
      verdict: "in_progress",
      verdict_reason:
        "Hermes 원장에 아직 끝나지 않은 작업으로 기록되어 있습니다.",
      summary: null,
      error: null,
      started_at: new Date(now - 95 * 60_000).toISOString(),
      completed_at: null,
      next_action: "완료 전까지 기다리기",
      provenance_verified: true,
      inspectable: true,
      evidence_fingerprint:
        "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
      review_state: "unreviewed",
      reviewed_at: null,
      workspace_evidence: {
        state: "in_progress",
        captured_before: new Date(now - 95 * 60_000).toISOString(),
        observed_at: new Date(now - 2 * 60_000).toISOString(),
        finalized: false,
        repository_root: "/Users/you/projects/agent-research",
        baseline_head: "0123456789abcdef0123456789abcdef01234567",
        observed_head: "0123456789abcdef0123456789abcdef01234567",
        head_changed: false,
        preexisting_dirty_count: 0,
        observed_dirty_count: 1,
        changed_files: [
          {
            path: "notes/memory-index-findings.md",
            before_status: null,
            after_status: "??",
            change: "added",
          },
        ],
        attribution:
          "실행 직전 기준선과 현재 작업공간의 중간 비교입니다. 완료 근거가 아닙니다.",
        warning: "실행이 끝나기 전의 중간 관측입니다.",
      },
    },
  ],
};

const previewNightRunDetails: Record<string, NightRunDetail> = {
  "turn-preview-codex": {
    generated_at: new Date().toISOString(),
    surface: "codex",
    task_id: "turn-preview-codex",
    thread_id: "co1",
    turn_id: "turn-preview-codex",
    title: "Codex 야간 실행 복구와 Morning Review 연결",
    project: "godofsessions",
    workspace: "/Users/you/projects/godofsessions",
    task_status: "completed",
    body:
      "Overnight goal\nCodex 야간 실행 복구와 Morning Review 연결\n\nOutcome\nCodex turn을 provider rollout에서 복구해 통합 아침 화면에 표시한다.\n\nVerification\n관련 Rust 테스트와 UI 빌드를 통과한다.\n\nConstraints\n외부 부작용과 자동 재시도를 금지한다.",
    assignee: null,
    max_runtime_seconds: null,
    goal_mode: false,
    goal_max_turns: null,
    max_retries: null,
    idempotency_key: "gos-codex-preview-done",
    provenance_verified: true,
    verdict: "ready_to_review",
    verdict_reason:
      "Codex 완료 수명주기와 최종 응답이 모두 있습니다. 실제 변경과 검증은 사람이 확인해야 합니다.",
    attempts: [
      {
        run_id: 1,
        profile: "Codex app-server",
        status: "completed",
        outcome: "completed",
        started_at: new Date(now - 7 * 60 * 60_000).toISOString(),
        ended_at: new Date(now - 4 * 60 * 60_000).toISOString(),
        duration_seconds: 10_800,
        worker_pid: null,
        summary:
          "Codex rollout 기반 중복 방지와 아침 실행 기록 복구를 구현하고 관련 테스트를 통과했습니다.",
        error: null,
      },
    ],
    events: [
      {
        event_id: 1,
        run_id: 1,
        kind: "submitted",
        created_at: new Date(now - 7 * 60 * 60_000).toISOString(),
        note: "Night Contract가 provider turn에 기록됨",
      },
      {
        event_id: 2,
        run_id: 1,
        kind: "agent_message",
        created_at: new Date(now - 4 * 60 * 60_000 - 5_000).toISOString(),
        note: "통합 아침 화면과 검증을 완료했습니다.",
      },
      {
        event_id: 3,
        run_id: 1,
        kind: "completed",
        created_at: new Date(now - 4 * 60 * 60_000).toISOString(),
        note: null,
      },
    ],
    warnings: [],
    read_only: true,
    methodology:
      "Codex thread index와 provider rollout을 읽기 전용으로 결합했습니다. clientUserMessageId가 God of Sessions 계약 출처를 증명합니다.",
  },
  "task-night-running": {
    generated_at: new Date().toISOString(),
    surface: "hermes",
    task_id: "task-night-running",
    thread_id: null,
    turn_id: null,
    title: "에이전트 메모리 인덱스 검증",
    project: "overnight-eval",
    workspace: "/Users/you/projects/overnight-eval",
    task_status: "running",
    body:
      "Outcome: 메모리 인덱스 경계와 누락 사례를 검증한다.\nVerification: 관련 테스트와 재현 명령을 통과시킨다.\nConstraints: 기존 데이터는 읽기 전용으로 취급한다.\nBoundaries: 외부 서비스 호출과 배포를 하지 않는다.\nStop when: 테스트 증거와 인계 요약이 준비된다.",
    assignee: "default",
    max_runtime_seconds: 25_200,
    goal_mode: true,
    goal_max_turns: 20,
    max_retries: 1,
    idempotency_key: "gos-night-preview-running",
    provenance_verified: true,
    verdict: "in_progress",
    verdict_reason:
      "Hermes 원장에 아직 끝나지 않은 작업으로 기록되어 있습니다.",
    attempts: [
      {
        run_id: 14,
        profile: "default",
        status: "running",
        outcome: null,
        started_at: new Date(now - 94 * 60_000).toISOString(),
        ended_at: null,
        duration_seconds: null,
        worker_pid: 48102,
        summary: null,
        error: null,
      },
    ],
    events: [
      {
        event_id: 21,
        run_id: null,
        kind: "created",
        created_at: new Date(now - 95 * 60_000).toISOString(),
        note: null,
      },
      {
        event_id: 22,
        run_id: 14,
        kind: "claimed",
        created_at: new Date(now - 94 * 60_000).toISOString(),
        note: "profile: default",
      },
      {
        event_id: 23,
        run_id: 14,
        kind: "spawned",
        created_at: new Date(now - 94 * 60_000 + 4_000).toISOString(),
        note: "pid: 48102",
      },
      {
        event_id: 24,
        run_id: 14,
        kind: "heartbeat",
        created_at: new Date(now - 4 * 60_000).toISOString(),
        note: null,
      },
    ],
    warnings: [],
    read_only: true,
    methodology:
      "Hermes task, task_runs, task_events를 읽기 전용으로 결합했습니다. 완료 이벤트는 실행 수명주기를 증명하지만 결과의 정확성까지 자동 증명하지는 않습니다.",
  },
  "task-night-done": {
    generated_at: new Date().toISOString(),
    surface: "hermes",
    task_id: "task-night-done",
    thread_id: null,
    turn_id: null,
    title: "세션 커넥터 경계와 회귀 테스트 정리",
    project: "control-plane-notes",
    workspace: "/Users/you/projects/control-plane-notes",
    task_status: "done",
    body:
      "Outcome: 커넥터별 읽기 경계를 문서화하고 회귀 테스트를 추가한다.\nVerification: 전체 자동 테스트와 문서 링크를 확인한다.\nConstraints: 세션 원본을 수정하지 않는다.\nBoundaries: 커밋, 배포, 외부 메시지를 하지 않는다.\nStop when: 테스트 통과와 변경 요약이 모두 남는다.",
    assignee: "default",
    max_runtime_seconds: 10_800,
    goal_mode: true,
    goal_max_turns: 20,
    max_retries: 1,
    idempotency_key: "gos-night-preview-done",
    provenance_verified: true,
    verdict: "ready_to_review",
    verdict_reason:
      "Hermes 완료 수명주기와 작업자의 인계 요약이 모두 있습니다. 실제 변경과 검증은 사람이 확인해야 합니다.",
    attempts: [
      {
        run_id: 9,
        profile: "default",
        status: "done",
        outcome: "completed",
        started_at: new Date(
          now - 11 * 60 * 60_000 + 60_000,
        ).toISOString(),
        ended_at: new Date(now - 8 * 60 * 60_000).toISOString(),
        duration_seconds: 10_740,
        worker_pid: 47381,
        summary:
          "커넥터별 읽기 경계를 문서화하고 관련 테스트를 추가했습니다. 검증 명령은 모두 통과했습니다.",
        error: null,
      },
    ],
    events: [
      {
        event_id: 11,
        run_id: null,
        kind: "created",
        created_at: new Date(now - 11 * 60 * 60_000).toISOString(),
        note: null,
      },
      {
        event_id: 12,
        run_id: 9,
        kind: "spawned",
        created_at: new Date(
          now - 11 * 60 * 60_000 + 62_000,
        ).toISOString(),
        note: "pid: 47381",
      },
      {
        event_id: 13,
        run_id: 9,
        kind: "completed",
        created_at: new Date(now - 8 * 60 * 60_000).toISOString(),
        note: "outcome: completed",
      },
    ],
    warnings: [],
    read_only: true,
    methodology:
      "Hermes task, task_runs, task_events를 읽기 전용으로 결합했습니다. 완료 이벤트는 실행 수명주기를 증명하지만 결과의 정확성까지 자동 증명하지는 않습니다.",
  },
};

export const previewNightPlanHistory: NightPlanHistory = {
  generated_at: new Date().toISOString(),
  plans: [
    {
      idempotency_key: "gos-portfolio-preview-m18",
      state: "needs_attention",
      approved_at: new Date(now - 15 * 60_000).toISOString(),
      deadline_at: new Date(now + 6.75 * 3_600_000).toISOString(),
      worker_pid: 73142,
      recovery_state: "recoverable",
      error: null,
      lanes: [
        {
          capacity_pool: "codex_subscription",
          items: [
            {
              draft_id: "night:1:godofsessions:codex:native",
              project: "godofsessions",
              surface: "codex",
              capacity_pool: "codex_subscription",
              state: "running",
              starts_after_hours: 0,
              time_budget_hours: 3.5,
              not_before_at: new Date(now - 15 * 60_000).toISOString(),
              latest_start_at: new Date(now + 3.25 * 60 * 60_000).toISOString(),
              started_at: new Date(now - 14 * 60_000).toISOString(),
              completed_at: null,
              idempotency_key: "gos-codex-preview",
              error: null,
              waiting_reason: null,
              waiting_kind: null,
            },
          ],
        },
        {
          capacity_pool: "grok_subscription",
          items: [
            {
              draft_id: "night:2:agent-research:hermes:default",
              project: "agent-research",
              surface: "hermes",
              capacity_pool: "grok_subscription",
              state: "running",
              starts_after_hours: 0,
              time_budget_hours: 2.5,
              not_before_at: new Date(now - 15 * 60_000).toISOString(),
              latest_start_at: new Date(now + 4.25 * 60 * 60_000).toISOString(),
              started_at: new Date(now - 13 * 60_000).toISOString(),
              completed_at: null,
              idempotency_key: "gos-night-preview",
              error: null,
              waiting_reason: null,
              waiting_kind: null,
            },
          ],
        },
        {
          capacity_pool: "claude_subscription",
          items: [
            {
              draft_id: "night:3:malgun-app:claude:native",
              project: "malgun-app",
              surface: "claude",
              capacity_pool: "claude_subscription",
              state: "pending",
              starts_after_hours: 0,
              time_budget_hours: 2,
              not_before_at: new Date(now - 15 * 60_000).toISOString(),
              latest_start_at: new Date(now + 4.75 * 60 * 60_000).toISOString(),
              started_at: null,
              completed_at: null,
              idempotency_key: "gos-claude-preview",
              error: null,
              waiting_reason:
                "Claude 구독의 5시간 창에 0.0%만 남았습니다. 초기화 뒤 승인한 마감 안에서 다시 확인합니다.",
              waiting_kind: "capacity",
            },
          ],
        },
      ],
    },
  ],
  warnings: [],
  read_only: true,
  methodology:
    "승인 시 고정한 coordinator 계획 원장과 공급자 실행 근거를 함께 표시합니다.",
};

export function previewNightRunDetail(taskId: string): NightRunDetail {
  const detail = previewNightRunDetails[taskId];
  if (!detail) throw new Error("미리보기 실행 기록을 찾지 못했습니다.");
  return detail;
}

export const previewOvernightPlan: OvernightPlan = {
  generated_at: new Date().toISOString(),
  evidence_window_hours: 24,
  sleep_hours: 7,
  sessions_considered: 12,
  projects_considered: 4,
  read_only: true,
  methodology:
    "최근성·반복 활동·구체적 제목·재개 가능한 컨텍스트·남은 사용량을 함께 평가했습니다. 작은 할당량 차이보다 기존 프로젝트 맥락을 우선합니다.",
  host_readiness: {
    observed_at: new Date().toISOString(),
    state: "needs_attention",
    read_only: true,
    methodology:
      "macOS 전원 소스, idle-sleep 보호, 노트북 덮개 제약, 작업공간 디스크 여유를 읽기 전용으로 확인했습니다.",
    checks: [
      {
        key: "power",
        level: "pass",
        label: "전원",
        message: "AC 전원 연결 · 배터리 100%",
        action: null,
      },
      {
        key: "idle_sleep",
        level: "pass",
        label: "Idle sleep",
        message: "coordinator가 caffeinate -i 아래에서 실행됩니다.",
        action: null,
      },
      {
        key: "lid",
        level: "warning",
        label: "MacBook 덮개",
        message:
          "caffeinate는 덮개를 닫아 생기는 sleep까지 보장하지 않습니다.",
        action: "덮개를 열어두거나 전원 연결된 정상 clamshell 환경 사용",
      },
      {
        key: "disk",
        level: "pass",
        label: "디스크",
        message: "선택된 작업공간에 최소 48.2 GiB가 남아 있습니다.",
        action: null,
      },
    ],
  },
  budgets: [
    {
      provider: "claude",
      state: "ready",
      plan: null,
      windows: [
        {
          label: "5시간",
          used_percent: 2,
          resets_at: new Date(now + 4 * 60 * 60 * 1000).toISOString(),
        },
        {
          label: "7일",
          used_percent: 2,
          resets_at: new Date(now + 6 * 86_400_000).toISOString(),
        },
      ],
      credits: null,
      observed_at: new Date().toISOString(),
      source_label: "OpenClaw usage adapter",
      message: null,
    },
    {
      provider: "codex",
      state: "ready",
      plan: "Pro",
      windows: [
        {
          label: "7일",
          used_percent: 13,
          resets_at: new Date(now + 6 * 86_400_000).toISOString(),
        },
      ],
      credits: "리셋권 2개",
      observed_at: new Date().toISOString(),
      source_label: "Codex app-server",
      message: null,
    },
    {
      provider: "grok",
      state: "ready",
      plan: "SuperGrok Heavy",
      windows: [
        {
          label: "7일",
          used_percent: 28,
          resets_at: new Date(now + 2 * 86_400_000).toISOString(),
        },
      ],
      credits: null,
      observed_at: new Date().toISOString(),
      source_label: "Grok ACP billing",
      message: null,
    },
  ],
  route_inventory: {
    generated_at: new Date().toISOString(),
    warnings: [],
    methodology:
      "실행 화면과 실제 모델 제공자, 차감되는 구독 풀을 분리했습니다. 여러 실행 경로가 같은 구독을 쓰면 하나의 용량으로 취급합니다.",
    routes: [
      {
        id: "claude:native",
        surface: "claude",
        model_provider: "claude",
        model: null,
        runtime: "Claude Code",
        capacity_pool: "claude_subscription",
        state: "ready",
        configured: true,
        capabilities: ["resume_session", "mcp"],
        adapter_readiness: "contract_ready",
        dispatch_interface: "Claude Code detached print worker",
        receipt_source: "forked Claude transcript + JSON result",
        dispatch_guardrails: [
          "기존 세션 컨텍스트는 fork하고 원본 세션은 보존",
          "dontAsk + 명시적 built-in tool 집합",
          "workspace 중심 read/write, network deny, 민감 환경변수 제거",
          "엄격한 OS sandbox와 sandbox escape 차단",
          "bypassPermissions 금지",
          "시간·turn 상한과 공급자 transcript idempotency marker 필수",
        ],
        source_label: "~/.local/bin/claude",
        message: null,
        limitations: [],
      },
      {
        id: "codex:native",
        surface: "codex",
        model_provider: "codex",
        model: null,
        runtime: "Codex app-server",
        capacity_pool: "codex_subscription",
        state: "ready",
        configured: true,
        capabilities: ["resume_session", "mcp", "native_sandbox"],
        adapter_readiness: "contract_ready",
        dispatch_interface: "Codex app-server JSON-RPC",
        receipt_source: "thread + turn + item events",
        dispatch_guardrails: [
          "workspace-write sandbox 고정",
          "danger-full-access 금지",
        ],
        source_label: "ChatGPT.app / Codex",
        message: null,
        limitations: [],
      },
      {
        id: "grok:native",
        surface: "grok",
        model_provider: "grok",
        model: null,
        runtime: "Grok Build ACP",
        capacity_pool: "grok_subscription",
        state: "ready",
        configured: true,
        capabilities: ["resume_session", "mcp"],
        adapter_readiness: "contract_ready",
        dispatch_interface: "Grok ACP stdio",
        receipt_source: "ACP session/update + completion",
        dispatch_guardrails: [
          "ACP 권한 요청을 앱이 명시적으로 판정",
          "--always-approve 금지",
        ],
        source_label: "~/.grok/bin/grok",
        message: null,
        limitations: [],
      },
      {
        id: "hermes:default",
        surface: "hermes",
        model_provider: "grok",
        model: "grok-4.5",
        runtime: "Hermes agent loop",
        capacity_pool: "grok_subscription",
        state: "ready",
        configured: true,
        capabilities: [
          "resume_session",
          "goal_loop",
          "mcp",
          "cross_session_memory",
        ],
        adapter_readiness: "contract_ready",
        dispatch_interface: "Hermes Kanban goal worker",
        receipt_source: "Hermes task_events + task_runs",
        dispatch_guardrails: [
          "idempotency key 필수",
          "max-runtime과 goal-max-turns 필수",
          "--yolo 금지",
        ],
        source_label: "Hermes config.yaml",
        message: null,
        limitations: [],
      },
    ],
  },
  candidates: [
    {
      rank: 1,
      project: "godofsessions",
      cwd: "/Users/you/projects/godofsessions",
      goal: "Overnight 추천 수직 슬라이스 — 검증 가능한 결과까지 진행",
      provider: "codex",
      execution_route_id: "codex:native",
      execution_surface: "codex",
      capacity_pool: "codex_subscription",
      route_reason:
        "기존 Codex 세션을 그대로 이어 컨텍스트 전환 비용을 줄입니다.",
      native_session_id: "co1",
      resume_existing: true,
      score: 91.4,
      confidence: "high",
      evidence: [
        "최근 24시간에 godofsessions 관련 세션 4개",
        "가장 최근 근거: “네 공급자 커넥터 구현” · 약 1시간 전",
        "3개 도구에서 같은 프로젝트 맥락이 발견됨",
      ],
      source_session_ids: ["codex:co1", "claude:cl1", "grok:g1"],
      provider_reason:
        "Codex에 이 프로젝트를 이어갈 세션이 있고, 가장 제한적인 사용량 창도 약 87% 남아 있습니다.",
      expected_outcome:
        "범위가 분리된 변경 세트와 테스트·검증 결과, 남은 장애물의 아침 보고",
      verification: [
        "프로젝트의 기존 테스트·타입 검사·빌드 중 관련 검증을 통과할 것",
        "변경 범위와 생성된 산출물을 아침 보고에 명시할 것",
        "검증할 수 없거나 막히면 추측으로 완료 처리하지 말고 원인을 남길 것",
      ],
      risks: [
        "대화 본문이 아닌 로컬 메타데이터만으로 목표를 추론했습니다.",
      ],
      estimated_hours: 3.5,
    },
    {
      rank: 2,
      project: "agent-research",
      cwd: "/Users/you/projects/agent-research",
      goal: "로컬 에이전트 시장 조사 — 검증 가능한 결과까지 진행",
      provider: "grok",
      execution_route_id: "hermes:default",
      execution_surface: "hermes",
      capacity_pool: "grok_subscription",
      route_reason:
        "Hermes의 goal 루프와 전용 작업 보드로 종료 조건까지 추적합니다.",
      native_session_id: null,
      resume_existing: false,
      score: 78.2,
      confidence: "medium",
      evidence: [
        "최근 24시간에 agent-research 관련 세션 2개",
        "가장 최근 근거: “로컬 에이전트 시장 조사” · 약 2시간 전",
        "2개 도구에서 같은 프로젝트 맥락이 발견됨",
      ],
      source_session_ids: ["grok:g1", "codex:co2"],
      provider_reason:
        "Hermes가 Grok 구독을 사용하면서 여러 세션의 조사 맥락을 새 goal로 묶을 수 있습니다.",
      expected_outcome: "근거 링크가 포함된 경쟁 제품 비교와 남은 조사 질문",
      verification: ["모든 핵심 주장에 출처가 있을 것"],
      risks: ["조사 범위가 열려 있어 종료 조건을 더 좁혀야 할 수 있습니다."],
      estimated_hours: 2.5,
    },
    {
      rank: 3,
      project: "malgun-app",
      cwd: "/Users/you/projects/malgun-app",
      goal: "첫 사용 예약 흐름의 회귀를 고치고 검증 가능한 상태로 마무리",
      provider: "claude",
      execution_route_id: "claude:native",
      execution_surface: "claude",
      capacity_pool: "claude_subscription",
      route_reason:
        "기존 Claude 세션을 보존한 채 strict sandbox 안의 새 fork로 이어갑니다.",
      native_session_id: "cl1",
      resume_existing: true,
      score: 73.8,
      confidence: "medium",
      evidence: [
        "최근 24시간에 malgun-app 관련 세션 3개",
        "가장 최근 근거: “첫 사용 예약 흐름 점검” · 약 3시간 전",
        "Claude 세션의 작업공간과 로컬 transcript가 일치함",
      ],
      source_session_ids: ["claude:cl1", "codex:co3"],
      provider_reason:
        "Claude 구독 여유가 크고 이 프로젝트의 유휴 기존 세션을 안전하게 fork할 수 있습니다.",
      expected_outcome:
        "관련 화면의 회귀 수정, 테스트 결과, 사람이 확인할 남은 위험의 아침 보고",
      verification: [
        "관련 테스트와 타입 검사를 통과할 것",
        "실패가 남으면 재현 조건과 막힌 지점을 명시할 것",
      ],
      risks: [
        "MCP와 네트워크가 차단되어 외부 서비스가 필요한 검증은 수행하지 않습니다.",
      ],
      estimated_hours: 2,
    },
  ],
  run_drafts: [
    {
      id: "night:1:godofsessions:codex:native",
      candidate_rank: 1,
      project: "godofsessions",
      route_id: "codex:native",
      format: "structured_prompt",
      run_mode: "resume_existing",
      native_session_id: "co1",
      workspace: "/Users/you/projects/godofsessions",
      time_budget_hours: 3.5,
      continuation_turn_budget: null,
      goal: "Overnight 추천 수직 슬라이스 — 검증 가능한 결과까지 진행",
      contract: {
        outcome:
          "범위가 분리된 변경 세트와 테스트·검증 결과, 남은 장애물의 아침 보고",
        verification:
          "프로젝트의 기존 테스트·타입 검사·빌드 중 관련 검증을 통과할 것 / 변경 범위와 생성된 산출물을 아침 보고에 명시할 것 / 검증할 수 없거나 막히면 추측으로 완료 처리하지 말고 원인을 남길 것",
        constraints:
          "기존 동작과 사용자의 관련 없는 변경을 보존할 것. 외부 메시지 전송, 게시, 배포, push, merge, 삭제, 구매, 결제를 하지 말 것. 검증 근거 없이 완료라고 보고하지 말 것.",
        boundaries:
          "/Users/you/projects/godofsessions 작업공간 안의 이 목표와 직접 관련된 파일·테스트·로컬 도구만 사용",
        stop_when:
          "자격 증명·사람의 결정·외부 시스템 변경·파괴적 작업이 필요하거나 관련 없는 기존 실패 때문에 검증할 수 없으면 막힌 이유를 남길 것. 목표가 일찍 끝나면 시간을 채우기 위한 새 일을 만들지 말 것.",
      },
      prompt:
        "Overnight goal\nOvernight 추천 수직 슬라이스 — 검증 가능한 결과까지 진행\n\nOutcome\n범위가 분리된 변경 세트와 테스트·검증 결과, 남은 장애물의 아침 보고\n\nVerification\n프로젝트의 기존 테스트·타입 검사·빌드 중 관련 검증을 통과할 것\n\nConstraints\n외부 메시지 전송, 게시, 배포, push, merge, 삭제, 구매, 결제를 하지 말 것.\n\nBoundaries\n/Users/you/projects/godofsessions\n\nStop and report when\n사람의 결정이나 외부 시스템 변경이 필요할 때",
      permission_profile: "workspace_write",
      external_side_effects_allowed: false,
      approval_required: true,
      dispatch_supported: true,
    },
    {
      id: "night:2:agent-research:hermes:default",
      candidate_rank: 2,
      project: "agent-research",
      route_id: "hermes:default",
      format: "hermes_goal",
      run_mode: "new_session",
      native_session_id: null,
      workspace: "/Users/you/projects/agent-research",
      time_budget_hours: 2.5,
      continuation_turn_budget: 20,
      goal: "로컬 에이전트 시장 조사 — 검증 가능한 결과까지 진행",
      contract: {
        outcome: "근거 링크가 포함된 경쟁 제품 비교와 남은 조사 질문",
        verification: "모든 핵심 주장에 출처가 있을 것",
        constraints:
          "기존 동작과 사용자의 관련 없는 변경을 보존할 것. 외부 메시지 전송, 게시, 배포, push, merge, 삭제, 구매, 결제를 하지 말 것.",
        boundaries:
          "/Users/you/projects/agent-research 작업공간 안의 이 목표와 직접 관련된 파일·테스트·로컬 도구만 사용",
        stop_when:
          "사람의 결정이나 외부 시스템 변경이 필요하면 막힌 이유를 남길 것. 목표가 일찍 끝나면 시간을 채우기 위한 새 일을 만들지 말 것.",
      },
      prompt:
        "/goal 로컬 에이전트 시장 조사 — 검증 가능한 결과까지 진행\n\nOutcome: 근거 링크가 포함된 경쟁 제품 비교와 남은 조사 질문\nVerification: 모든 핵심 주장에 출처가 있을 것\nConstraints: 기존 동작과 사용자의 관련 없는 변경을 보존하고 외부 부작용을 만들지 말 것\nBoundaries: /Users/you/projects/agent-research 안의 조사 산출물과 검증만 수행\nStop when: 사람의 결정이나 외부 시스템 변경이 필요하거나 목표를 검증했을 때",
      permission_profile: "workspace_write",
      external_side_effects_allowed: false,
      approval_required: true,
      dispatch_supported: true,
    },
    {
      id: "night:3:malgun-app:claude:native",
      candidate_rank: 3,
      project: "malgun-app",
      route_id: "claude:native",
      format: "structured_prompt",
      run_mode: "resume_existing",
      native_session_id: "cl1",
      workspace: "/Users/you/projects/malgun-app",
      time_budget_hours: 2,
      continuation_turn_budget: null,
      goal: "첫 사용 예약 흐름의 회귀를 고치고 검증 가능한 상태로 마무리",
      contract: {
        outcome:
          "관련 화면의 회귀 수정, 테스트 결과, 사람이 확인할 남은 위험의 아침 보고",
        verification:
          "관련 테스트와 타입 검사를 통과할 것 / 실패가 남으면 재현 조건과 막힌 지점을 명시할 것",
        constraints:
          "기존 동작과 관련 없는 변경을 보존하고 외부 메시지, 배포, push, merge, 삭제를 하지 말 것.",
        boundaries:
          "/Users/you/projects/malgun-app 작업공간 안의 관련 파일과 로컬 검증만 사용",
        stop_when:
          "사람의 결정, 외부 시스템, 자격 증명, 파괴적 작업이 필요하면 이유를 남기고 멈출 것.",
      },
      prompt:
        "Overnight goal\n첫 사용 예약 흐름의 회귀를 고치고 검증 가능한 상태로 마무리\n\nOutcome\n관련 화면의 회귀 수정과 테스트 결과\n\nVerification\n관련 테스트와 타입 검사를 통과할 것\n\nConstraints\n외부 메시지, 배포, push, merge, 삭제를 하지 말 것.\n\nBoundaries\n/Users/you/projects/malgun-app\n\nStop and report when\n사람의 결정이나 외부 시스템 변경이 필요할 때",
      permission_profile: "workspace_write",
      external_side_effects_allowed: false,
      approval_required: true,
      dispatch_supported: true,
    },
  ],
  schedule: {
    parallel: true,
    methodology:
      "같은 구독 풀의 작업은 한 번에 하나씩 순차 실행하고, 서로 다른 구독 풀은 동시에 시작합니다. 각 레인의 합은 수면시간을 넘지 않습니다.",
    lanes: [
      {
        capacity_pool: "codex_subscription",
        planned_hours: 3.5,
        slots: [
          {
            candidate_rank: 1,
            project: "godofsessions",
            route_id: "codex:native",
            starts_after_hours: 0,
            time_budget_hours: 3.5,
          },
        ],
      },
      {
        capacity_pool: "grok_subscription",
        planned_hours: 2.5,
        slots: [
          {
            candidate_rank: 2,
            project: "agent-research",
            route_id: "hermes:default",
            starts_after_hours: 0,
            time_budget_hours: 2.5,
          },
        ],
      },
      {
        capacity_pool: "claude_subscription",
        planned_hours: 2,
        slots: [
          {
            candidate_rank: 3,
            project: "malgun-app",
            route_id: "claude:native",
            starts_after_hours: 0,
            time_budget_hours: 2,
          },
        ],
      },
    ],
  },
  dispatch_preflights: [
    {
      draft_id: "night:1:godofsessions:codex:native",
      state: "ready_for_approval",
      surface: "codex",
      adapter: "Codex app-server v2",
      scope_label: "writable root",
      scope_value: "/Users/you/projects/godofsessions",
      executor_label: "기존 thread",
      executor_value: "co1",
      transport: "stdio JSONL · shell 없음 · networkAccess false",
      idempotency_key: "gos-codex-89ca72cc88a44f313b17b294",
      checks: [
        {
          key: "route",
          level: "pass",
          label: "Codex 실행 경로",
          message:
            "Codex 구독, 로컬 로그인, app-server 경로가 준비되어 있습니다.",
        },
        {
          key: "binary",
          level: "pass",
          label: "앱 번들 실행기",
          message: "ChatGPT 앱 안의 실제 Codex 실행기를 사용합니다.",
        },
        {
          key: "auth",
          level: "pass",
          label: "Codex 로그인",
          message:
            "로컬 Codex 로그인 상태를 찾았습니다. 자격 증명 값은 읽지 않습니다.",
        },
        {
          key: "protocol",
          level: "pass",
          label: "app-server 호환성",
          message: "codex_cli_rs/0.145 · 사용 가능한 모델 8개",
        },
        {
          key: "workspace",
          level: "pass",
          label: "작업공간 경계",
          message:
            "정규화된 Git 작업공간 한 곳만 writable root로 사용합니다.",
        },
        {
          key: "contract",
          level: "pass",
          label: "Night Contract",
          message:
            "workspace-write, 외부 부작용 금지, 제한된 시간 예산이 고정되어 있습니다.",
        },
        {
          key: "thread",
          level: "pass",
          label: "Codex thread",
          message:
            "기존 thread가 같은 작업공간에 있고 현재 실행 중이 아니며 보관되지 않았습니다.",
        },
        {
          key: "idempotency",
          level: "pass",
          label: "중복 실행 방지",
          message:
            "provider rollout에 같은 clientUserMessageId가 없습니다.",
        },
      ],
      commands: [
        {
          step: "start_night_worker",
          program: "/usr/bin/caffeinate",
          arguments: [
            "-i",
            "/Applications/God of Sessions.app/Contents/MacOS/god-of-sessions",
            "--codex-night-worker",
          ],
          mutates_local_state: false,
          summary: "GUI와 분리된 유휴 절전 방지 야간 작업자 시작",
        },
        {
          step: "start_app_server",
          program: "/Applications/ChatGPT.app/Contents/Resources/codex",
          arguments: ["app-server", "--listen", "stdio://"],
          mutates_local_state: false,
          summary: "로컬 Codex app-server 전용 프로세스 시작",
        },
      ],
      protocol_requests: [
        {
          step: "initialize",
          method: "initialize",
          params: {
            clientInfo: {
              name: "god-of-sessions",
              title: "God of Sessions",
              version: "0.1.0",
            },
            capabilities: {},
          },
          mutates_local_state: false,
          summary: "안정 API로 클라이언트 초기화",
        },
        {
          step: "initialized",
          method: "initialized",
          params: {},
          mutates_local_state: false,
          summary: "초기화 완료 알림",
        },
        {
          step: "open_thread",
          method: "thread/resume",
          params: {
            threadId: "co1",
            cwd: "/Users/you/projects/godofsessions",
            approvalPolicy: "never",
            approvalsReviewer: "user",
            sandbox: "workspace-write",
            runtimeWorkspaceRoots: ["/Users/you/projects/godofsessions"],
            excludeTurns: true,
          },
          mutates_local_state: true,
          summary: "승인한 기존 thread를 같은 cwd로 재개",
        },
        {
          step: "start_turn",
          method: "turn/start",
          params: {
            threadId: "co1",
            clientUserMessageId: "gos-codex-89ca72cc88a44f313b17b294",
            input: [
              {
                type: "text",
                text: "Overnight goal\nOvernight 추천 수직 슬라이스 — 검증 가능한 결과까지 진행",
              },
            ],
            cwd: "/Users/you/projects/godofsessions",
            approvalPolicy: "never",
            approvalsReviewer: "user",
            sandboxPolicy: {
              type: "workspaceWrite",
              writableRoots: ["/Users/you/projects/godofsessions"],
              networkAccess: false,
              excludeSlashTmp: true,
              excludeTmpdirEnvVar: true,
            },
            runtimeWorkspaceRoots: ["/Users/you/projects/godofsessions"],
            environments: [],
          },
          mutates_local_state: true,
          summary:
            "외부 승인·네트워크 없이 정확한 Night Contract turn 시작",
        },
      ],
      expected_receipt:
        "thread/resume의 threadId + turn/start의 turnId + item 이벤트 + turn/completed 최종 상태",
      read_only: true,
      execution_enabled: false,
    },
    {
      draft_id: "night:2:agent-research:hermes:default",
      state: "ready_for_approval",
      surface: "hermes",
      adapter: "Hermes Kanban goal worker",
      scope_label: "격리 보드",
      scope_value: "god-of-sessions-night",
      executor_label: "작업자",
      executor_value: "default",
      transport: "셸을 거치지 않는 직접 argv",
      idempotency_key: "gos-night-1ec42a9d4fb8e3371b40",
      checks: [
        {
          key: "route",
          level: "pass",
          label: "Hermes 실행 경로",
          message: "현재 Hermes 경로와 Grok 구독이 준비되어 있습니다.",
        },
        {
          key: "binary",
          level: "pass",
          label: "Hermes 실행기",
          message: "로컬 Hermes 실행기를 찾았습니다.",
        },
        {
          key: "assignee",
          level: "pass",
          label: "격리 작업자",
          message: "기본 Hermes 프로필을 전용 보드 작업자로 사용할 수 있습니다.",
        },
        {
          key: "workspace",
          level: "pass",
          label: "작업공간",
          message: "정규화된 Git 작업공간 안으로 쓰기 범위를 고정합니다.",
        },
        {
          key: "contract",
          level: "pass",
          label: "Night Contract",
          message: "새 Hermes goal 작업이며 외부 부작용이 금지되어 있습니다.",
        },
        {
          key: "board",
          level: "info",
          label: "전용 보드",
          message:
            "승인 후 전용 보드를 새로 만들며 기본 보드는 건드리지 않습니다.",
        },
      ],
      commands: [
        {
          step: "ensure_board",
          program: "/Users/you/.local/bin/hermes",
          arguments: [
            "kanban",
            "boards",
            "create",
            "god-of-sessions-night",
            "--name",
            "God of Sessions Night",
            "--description",
            "Approval-gated overnight runs",
          ],
          mutates_local_state: true,
          summary: "격리된 Hermes 보드를 한 번만 생성",
        },
        {
          step: "create_task",
          program: "/Users/you/.local/bin/hermes",
          arguments: [
            "kanban",
            "--board",
            "god-of-sessions-night",
            "create",
            "--body",
            "Outcome: 근거 링크가 포함된 경쟁 제품 비교와 남은 조사 질문\nVerification: 모든 핵심 주장에 출처가 있을 것\nConstraints: 기존 동작과 사용자의 관련 없는 변경을 보존하고 외부 부작용을 만들지 말 것\nBoundaries: /Users/you/projects/agent-research 안의 조사 산출물과 검증만 수행\nStop when: 사람의 결정이나 외부 시스템 변경이 필요하거나 목표를 검증했을 때",
            "--assignee",
            "default",
            "--workspace",
            "dir:/Users/you/projects/agent-research",
            "--priority",
            "0",
            "--idempotency-key",
            "gos-night-1ec42a9d4fb8e3371b40",
            "--max-runtime",
            "150m",
            "--created-by",
            "god-of-sessions",
            "--max-retries",
            "1",
            "--goal",
            "--goal-max-turns",
            "20",
            "--json",
            "--",
            "로컬 에이전트 시장 조사 — 검증 가능한 결과까지 진행",
          ],
          mutates_local_state: true,
          summary: "승인된 계약과 동일한 goal 작업을 idempotent하게 생성",
        },
        {
          step: "dispatch_one",
          program: "/Users/you/.local/bin/hermes",
          arguments: [
            "kanban",
            "--board",
            "god-of-sessions-night",
            "dispatch",
            "--max",
            "1",
            "--failure-limit",
            "1",
            "--json",
          ],
          mutates_local_state: true,
          summary: "전용 보드에서 정확히 한 작업자만 시작",
        },
      ],
      protocol_requests: [],
      expected_receipt:
        "create JSON의 task id + dispatch spawned task id + task_events/task_runs의 pid/session",
      read_only: true,
      execution_enabled: false,
    },
    {
      draft_id: "night:3:malgun-app:claude:native",
      state: "ready_for_approval",
      surface: "claude",
      adapter: "Claude Code forked print worker",
      scope_label: "쓰기 가능한 Git 작업공간",
      scope_value: "/Users/you/projects/malgun-app",
      executor_label: "출처 세션 → 격리 fork",
      executor_value: "cl1",
      transport: "detached worker → Claude Code stdin",
      idempotency_key:
        "gos-claude-b8ea7721b803e85d37d2932aee4cc57c4f4aef716b53011d03a94845cd4c9853",
      checks: [
        {
          key: "route",
          level: "pass",
          label: "Claude 실행 경로",
          message: "Claude 구독과 네이티브 실행 경로가 준비되어 있습니다.",
        },
        {
          key: "version",
          level: "pass",
          label: "엄격한 sandbox 버전",
          message: "2.1.220 (Claude Code) · strict sandbox와 turn cap 지원",
        },
        {
          key: "auth",
          level: "pass",
          label: "Claude 구독 로그인",
          message: "claude.ai Max 구독 로그인 · 자격 증명 값은 읽지 않음",
        },
        {
          key: "session",
          level: "pass",
          label: "기존 세션 fork",
          message:
            "같은 작업공간의 유휴 세션 컨텍스트를 새 세션으로 fork합니다.",
        },
        {
          key: "workspace",
          level: "pass",
          label: "작업공간 경계",
          message:
            "정규화된 Git 작업공간 한 곳만 read/write 경계로 사용합니다.",
        },
        {
          key: "idempotency",
          level: "pass",
          label: "영수증·공급자 원장 중복 방지",
          message:
            "같은 로컬 실행 영수증이나 Claude transcript marker가 없습니다.",
        },
        {
          key: "contract",
          level: "pass",
          label: "Night Contract",
          message:
            "fork, workspace-write, 외부 부작용 금지, 시간 상한이 고정되어 있습니다.",
        },
      ],
      commands: [
        {
          step: "start_claude_night_worker",
          program: "/usr/bin/caffeinate",
          arguments: [
            "-i",
            "/Applications/God of Sessions.app/Contents/MacOS/god-of-sessions",
            "--claude-night-worker",
          ],
          mutates_local_state: false,
          summary:
            "GUI와 분리된 유휴 절전 방지 Claude 야간 작업자 시작",
        },
        {
          step: "fork_claude_session",
          program: "/Users/you/.local/bin/claude",
          arguments: [
            "--safe-mode",
            "--no-chrome",
            "--strict-mcp-config",
            "--mcp-config",
            '{"mcpServers":{}}',
            "--permission-mode",
            "dontAsk",
            "--settings",
            '{"permissions":{"defaultMode":"dontAsk","allow":["Read","Edit","Write","Glob","Grep","Bash"],"deny":["WebFetch","WebSearch","mcp__*","Agent","Bash(git push *)","Bash(gh *)"]},"sandbox":{"enabled":true,"autoAllowBashIfSandboxed":true,"allowUnsandboxedCommands":false,"failIfUnavailable":true,"filesystem":{"denyRead":["~/"],"allowRead":["/Users/you/projects/malgun-app"],"denyWrite":["~/"],"allowWrite":["/Users/you/projects/malgun-app"]},"network":{"allowedDomains":[]}}}',
            "--tools",
            "Bash,Edit,Read,Write,Glob,Grep",
            "--allowedTools",
            "Bash,Edit,Read,Write,Glob,Grep",
            "--max-turns",
            "20",
            "--output-format",
            "json",
            "--resume",
            "cl1",
            "--fork-session",
            "-p",
          ],
          mutates_local_state: true,
          summary:
            "기존 세션을 fork하고 Night Contract를 노출되지 않는 stdin으로 전달",
        },
      ],
      protocol_requests: [],
      expected_receipt:
        "원자적 worker 영수증 + fork된 Claude transcript의 marker/result",
      read_only: true,
      execution_enabled: false,
    },
  ],
  exclusions: [
    {
      project: "orca",
      reason: "이미 실행 중인 세션이 있어 중복 작업과 충돌 위험이 큽니다.",
    },
  ],
};
